spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springLabs
    username: admin
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-message: always
    include-binding-errors: always